package com.quiral.ventanas;

import com.quiral.util.UtilControlTablas;
import com.quiral.util.UtilFechas;
import com.quiral.util.UtilMonitor;
import com.quiral.util.UtilPropiedades;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * @author Teo
 */
public class CalendarioAgenda extends javax.swing.JFrame {
    
    UtilPropiedades propiedades = new UtilPropiedades();
    UtilMonitor monitor; //No puedo instanciarla aca porque requiere un "this", que no puede usarse hasta construir esta clase per se
    
    public CalendarioAgenda() {
        initComponents();
        inicializar();
        inicializarTablas();
        llenarCalendario();
    }
    
    private void inicializar(){
        monitor = new UtilMonitor(this, jPanel1, 0, 0);
        
        int altoEfectivoFrame = monitor.obtenerAltoUtilizableMaximoEnMonitorDinamico() - 50;
        jPanel1.setBounds(0, 0, jPanel1.getWidth(), altoEfectivoFrame);
        monitor.redimensionarReposicionarVentana();
        int nuevoAltoTabla = altoEfectivoFrame - jspCalendario.getY() - 5;
        jspCalendario.setBounds(jspCalendario.getX(), jspCalendario.getY(), jspCalendario.getWidth(), nuevoAltoTabla);
    }

    private void llenarCalendario(){
        List<LocalDate> lista = UtilFechas.obtenerRangoDesdeHoy(0);
        DefaultTableModel modelo = (DefaultTableModel)jtCalendario.getModel();
        String[] fila = {"-", "-", "-"};
        for(int i = 0; i < lista.size(); i++){
            fila[0] = lista.get(i).toString();
            modelo.addRow(fila);
        }
    }
    
    private void inicializarTablas(){
        String[] columnas = {"Fecha", "Dia", "Obs."};
        jtCalendario.setModel(UtilControlTablas.createDefaultTableModelGeneric(columnas));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jspCalendario = new javax.swing.JScrollPane();
        jtCalendario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calendario Interactivo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 540, 17);

        jspCalendario.setViewportView(jtCalendario);

        jPanel1.add(jspCalendario);
        jspCalendario.setBounds(10, 110, 520, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 540, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarioAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarioAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarioAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarioAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarioAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspCalendario;
    private javax.swing.JTable jtCalendario;
    // End of variables declaration//GEN-END:variables
}
