/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.teo.ventanas;

import com.teo.util.UtilFechas;
import com.teo.util.UtilGraficoVentanas;
import java.time.LocalDate;

/**
 *
 * @author Teo
 */
public class HubRegistroDiario extends javax.swing.JFrame {

    /**
     * Creates new form HubRegistroDiario
     */
    public HubRegistroDiario() {
        initComponents();
        UtilGraficoVentanas.reshapeadorVentanas(this, jPanel1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbHoy = new javax.swing.JButton();
        jbAyer = new javax.swing.JButton();
        jtxtFecha = new javax.swing.JFormattedTextField();
        jbActividadHoy = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbNuevoRegistroComida = new javax.swing.JButton();
        jbNuevoRegistroActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaObservaciones = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Lobby Diario");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(7, 10, 440, 16);

        jbHoy.setText("Hoy");
        jbHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHoyActionPerformed(evt);
            }
        });
        jPanel1.add(jbHoy);
        jbHoy.setBounds(130, 50, 72, 23);

        jbAyer.setText("Retroceder un dia");
        jPanel1.add(jbAyer);
        jbAyer.setBounds(210, 50, 230, 23);

        jtxtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel1.add(jtxtFecha);
        jtxtFecha.setBounds(10, 50, 110, 22);

        jbActividadHoy.setText("Cargar Actividad Fisica de hoy");
        jPanel1.add(jbActividadHoy);
        jbActividadHoy.setBounds(10, 90, 280, 40);

        jButton4.setText("Cargar Consumo de hoy");
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 140, 280, 40);

        jbNuevoRegistroComida.setText("Nueva Comida");
        jPanel1.add(jbNuevoRegistroComida);
        jbNuevoRegistroComida.setBounds(320, 140, 120, 40);

        jbNuevoRegistroActividad.setText("Nueva Act.");
        jbNuevoRegistroActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoRegistroActividadActionPerformed(evt);
            }
        });
        jPanel1.add(jbNuevoRegistroActividad);
        jbNuevoRegistroActividad.setBounds(320, 90, 120, 40);

        jtxtAreaObservaciones.setColumns(20);
        jtxtAreaObservaciones.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaObservaciones);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 420, 130);

        jLabel2.setText("Observaciones generales");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 190, 400, 16);

        jbGuardar.setText("Guardar");
        jPanel1.add(jbGuardar);
        jbGuardar.setBounds(345, 350, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 450, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHoyActionPerformed
        LocalDate fecha = UtilFechas.obtenerFechaHoy();
        jtxtFecha.setText(fecha.format(UtilFechas.FORMATO_DATETIME));
    }//GEN-LAST:event_jbHoyActionPerformed

    private void jbNuevoRegistroActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoRegistroActividadActionPerformed
        AbmModalGenerico.main(this, AbmModalGenerico.GUARDAR.ACTIVIDAD);
    }//GEN-LAST:event_jbNuevoRegistroActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HubRegistroDiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActividadHoy;
    private javax.swing.JButton jbAyer;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbHoy;
    private javax.swing.JButton jbNuevoRegistroActividad;
    private javax.swing.JButton jbNuevoRegistroComida;
    private javax.swing.JTextArea jtxtAreaObservaciones;
    private javax.swing.JFormattedTextField jtxtFecha;
    // End of variables declaration//GEN-END:variables
}
