package com.teo.ventanas;

import com.teo.util.UtilControlTablas;
import com.teo.util.UtilControlVentanas;
import com.teo.util.UtilFechas;
import com.teo.util.UtilGraficoVentanas;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;

/**
 * @author Teo
 */
public class Menu extends javax.swing.JFrame {
    
    UtilGraficoVentanas monitor; //No puedo instanciarla aca porque requiere un "this", que no puede usarse hasta construir esta clase per se
    
    public Menu() {
        initComponents();
        inicializar();
    }
    
    private void inicializar(){
        monitor = new UtilGraficoVentanas(this, jPanel1, 0, 0);
        monitor.redimensionarReposicionarVentana();
        inicializarCalendario();
        this.setVisible(true);
    }

    private void inicializarCalendario(){
        
        jtCalendario.setModel(UtilControlTablas.createDefaultTableModelGeneric(new String[]{"FECHA", "Actividades"}));
        DefaultTableModel modelo = (DefaultTableModel) jtCalendario.getModel();
        for(LocalDate fecha : UtilFechas.obtenerRangoDesdeHoy(30)){
            Object[] fila = new Object[2];
            fila[0] = fecha;
            fila[1] = "Libre";
            modelo.addRow(fila);
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jspCalendario = new javax.swing.JScrollPane();
        jtCalendario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calendario Interactivo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 14, 370, 15);

        jButton1.setText("Listado Personas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 60, 120, 23);

        jButton2.setText("Nueva Tarea");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 110, 120, 23);

        jButton3.setText("Nueva Persona");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 60, 120, 23);

        jspCalendario.setViewportView(jtCalendario);

        jPanel1.add(jspCalendario);
        jspCalendario.setBounds(20, 180, 360, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        UtilControlVentanas.setearFrameParaVolver(UtilControlVentanas.VOLVER_MENU);
        UtilControlVentanas.abrirAbmPersonas(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UtilControlVentanas.setearFrameParaVolver(UtilControlVentanas.VOLVER_MENU);
        UtilControlVentanas.abrirListado(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspCalendario;
    private javax.swing.JTable jtCalendario;
    // End of variables declaration//GEN-END:variables
}
