package com.teo.ventanas;

import com.teo.modelos.Tarea;
import com.teo.service.TareaSrv;
import com.teo.util.UtilControlTablas;
import com.teo.util.FlujoVentanas;
import com.teo.util.UtilGraficoVentanas;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author Teo
 */
public class Menu extends javax.swing.JFrame {
    
    
    
    public Menu() {
        initComponents();
        inicializar();
    }
    
    private void inicializar(){
        UtilGraficoVentanas.reshapeadorVentanas(this, jPanel1, 0, 0);
        inicializarCalendario();
        this.setVisible(true);
    }

    private void inicializarCalendario(){
        
        jtCalendario.setModel(UtilControlTablas.createDefaultTableModelGeneric(new String[]{"id", "Asunto", "Dias", "Fecha", "Prioridad"}));
        int fraccion = jtCalendario.getWidth() / 100;
        UtilControlTablas.setTableWidth(jtCalendario, new int[]{0, fraccion * 50, fraccion * 20, fraccion * 20 , fraccion * 10});
        DefaultTableModel modelo = (DefaultTableModel) jtCalendario.getModel();
        for(Tarea tarea : TareaSrv.obtenerTodasTareasFechadas()){
            Object[] fila = new Object[5];
            fila[0] = tarea.getId();
            fila[1] = tarea.getAsunto();
            
            if(tarea.isFechaLimite()){
                fila[2] = "QUEDAN " + tarea.getFecha().until(LocalDate.now(), ChronoUnit.DAYS) * (-1);
            } else {
                fila[2] = "Faltan " + tarea.getFecha().until(LocalDate.now(), ChronoUnit.DAYS) * (-1);
            }
            
            fila[3] = tarea.getFecha();
            fila[4] = tarea.getPrioridad();
            modelo.addRow(fila);
        }
        
        jtCalendarioSinFecha.setModel(UtilControlTablas.createDefaultTableModelGeneric(new String[]{"id", "Asunto", "Prioridad"}));
        fraccion = jtCalendarioSinFecha.getWidth() / 100;
        UtilControlTablas.setTableWidth(jtCalendarioSinFecha, new int[]{0, fraccion * 75, fraccion * 25});
        DefaultTableModel modeloNoFechado = (DefaultTableModel) jtCalendarioSinFecha.getModel();
        for(Tarea tarea : TareaSrv.obtenerTodasTareasSinFecha()){
            Object[] fila = new Object[3];
            fila[0] = tarea.getId();
            fila[1] = tarea.getAsunto();
            fila[2] = tarea.getPrioridad();
            modeloNoFechado.addRow(fila);
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jspCalendario1 = new javax.swing.JScrollPane();
        jtCalendarioSinFecha = new javax.swing.JTable();
        jspCalendario2 = new javax.swing.JScrollPane();
        jtCalendario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbHubDiario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OPEM - Menu Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calendario-Agenda Interactivo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(11, 14, 770, 30);

        jButton1.setText("Listado Personas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 60, 210, 50);

        jButton2.setText("Nueva Tarea");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 60, 160, 50);

        jButton3.setText("Nueva Persona");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 60, 190, 50);

        jspCalendario1.setViewportView(jtCalendarioSinFecha);

        jPanel1.add(jspCalendario1);
        jspCalendario1.setBounds(440, 170, 340, 310);

        jtCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtCalendarioMouseReleased(evt);
            }
        });
        jspCalendario2.setViewportView(jtCalendario);

        jPanel1.add(jspCalendario2);
        jspCalendario2.setBounds(20, 170, 410, 310);

        jLabel2.setText("Tareas sin Fecha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 150, 240, 16);

        jLabel3.setText("Tareas Proximas ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 150, 310, 16);

        jbHubDiario.setText("HubDiario");
        jbHubDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHubDiarioActionPerformed(evt);
            }
        });
        jPanel1.add(jbHubDiario);
        jbHubDiario.setBounds(30, 120, 190, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FlujoVentanas.setearFrameParaVolver(FlujoVentanas.FRAME_MENU);
        FlujoVentanas.abrirAbmPersonas(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FlujoVentanas.setearFrameParaVolver(FlujoVentanas.FRAME_MENU);
        FlujoVentanas.abrirListado(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FlujoVentanas.setearFrameParaVolver(FlujoVentanas.FRAME_MENU);
        FlujoVentanas.abrirAbmTareas(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtCalendarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCalendarioMouseReleased
        seleccionarEditarTarea(jtCalendario);
    }//GEN-LAST:event_jtCalendarioMouseReleased

    private void jbHubDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHubDiarioActionPerformed
        HubRegistroDiario.main();
        this.dispose();
    }//GEN-LAST:event_jbHubDiarioActionPerformed
    
    private void eliminarTarea(JTable tabla){
//        int id = UtilControlTablas.obtenerValorNumericoDeTabla(tabla, 0);
//        if(id != -1){
//            TareaSrv.eliminar(id);
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbHubDiario;
    private javax.swing.JScrollPane jspCalendario1;
    private javax.swing.JScrollPane jspCalendario2;
    private javax.swing.JTable jtCalendario;
    private javax.swing.JTable jtCalendarioSinFecha;
    // End of variables declaration//GEN-END:variables

    private void seleccionarEditarTarea(JTable tabla) {
        int fila = tabla.getSelectedRow();
        if(fila != -1){
            int id = Integer.parseInt(((DefaultTableModel)tabla.getModel()).getValueAt(fila, 0).toString());
            if(id != -1){
                FlujoVentanas.setearFrameParaVolver(FlujoVentanas.FRAME_MENU);
                FlujoVentanas.abrirAbmTareas(this, id);
            }
        }
    }
}
