/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.teo.ventanas;

import com.teo.util.UtilArchivos;
import com.teo.util.UtilGraficoVentanas;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class VisualizadorFotos extends javax.swing.JFrame {
   
    List<String> DIRECTORIO_LISTA = new ArrayList<>();
    String DIRECTORIO_PATH = "";
    int DIRECTORIO_INDICES = 0;
    ImageIcon[] CACHE_IMAGENES = new ImageIcon[3]; 
    
    public VisualizadorFotos() {
        initComponents();
        UtilGraficoVentanas.reshapeadorVentanas(this, jPanel2, 0, 0);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtxtDirectorio = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jtxtDirectorio.setText("D:\\Impresion-Grupo1");
        jPanel2.add(jtxtDirectorio);
        jtxtDirectorio.setBounds(6, 6, 438, 22);

        jbBuscar.setText("Go!");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscar);
        jbBuscar.setBounds(450, 6, 72, 23);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Foto Aqui");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(6, 35, 516, 388);

        jButton1.setText("--->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(372, 429, 150, 40);

        jButton2.setText("<---");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(6, 429, 150, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        DIRECTORIO_PATH = jtxtDirectorio.getText().trim();
        this.DIRECTORIO_LISTA = UtilArchivos.obtenerArchivosEnDirectorioString(DIRECTORIO_PATH, false, false);
        CACHE_IMAGENES[1] = obtenerImagenSegunIndice(DIRECTORIO_INDICES);
        CACHE_IMAGENES[2] = obtenerImagenSegunIndice(DIRECTORIO_INDICES+1);
        
        mostrarImagen();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        avanzarCache();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        retrocederCache();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarImagen(){
        if(!DIRECTORIO_LISTA.isEmpty()){
            jLabel1.setText("");
            jLabel1.setIcon(CACHE_IMAGENES[1]);
        } else {
            jLabel1.setText("Nada que mostrar.");
        }
    }
    
    private synchronized ImageIcon obtenerImagenSegunIndice(int indice){
        ImageIcon icon = new ImageIcon(DIRECTORIO_PATH + File.separator + DIRECTORIO_LISTA.get(indice));
        Image imagen = icon.getImage();
        imagen = imagen.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), java.awt.Image.SCALE_SMOOTH);
        icon = new ImageIcon(imagen);
        return icon;
    }
    
    private void retrocederCache(){
        if(DIRECTORIO_LISTA.isEmpty()){
            return;
        }
        if(DIRECTORIO_INDICES > 0){
            CACHE_IMAGENES[2] = CACHE_IMAGENES[1];
            CACHE_IMAGENES[1] = CACHE_IMAGENES[0];
            mostrarImagen();
            DIRECTORIO_INDICES--;
            if(DIRECTORIO_INDICES > 0){
                CACHE_IMAGENES[0] = obtenerImagenSegunIndice(DIRECTORIO_INDICES-1);
            } else {
                CACHE_IMAGENES[0] = null;
            }
        }
    }
    
    private synchronized void avanzarCache(){
        if(DIRECTORIO_LISTA.isEmpty()){
            return;
        }
        CACHE_IMAGENES[0] = CACHE_IMAGENES[1];
        CACHE_IMAGENES[1] = CACHE_IMAGENES[2];
        mostrarImagen();
        DIRECTORIO_INDICES++;
        new Thread(() -> {
            CACHE_IMAGENES[2] = obtenerImagenSegunIndice(DIRECTORIO_INDICES+1);
        }).start();
        
    }
    
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizadorFotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizadorFotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizadorFotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizadorFotos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizadorFotos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JTextField jtxtDirectorio;
    // End of variables declaration//GEN-END:variables
}
